name: Run Static Tests and Test Suite

on:
  pull_request:
    types: [opened]

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Run static test
        run: yarn lint

      - name: Run test suite
        run: yarn test:ci

      - name: Startup app as localhost
        run: yarn dev

      - name: Run a11y test
        run: yarn test:a11y
