# Not working yet
name: Run Static Tests and Test Suite

on: deployment_status

jobs:
  verify:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get Vercel preview URL
        id: get_preview_url
        uses: actions/github-script@5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment;
            const regex = /https:\/\/[a-z0-9-]+\.vercel\.app/g;
            const matches = comment.body.match(regex);
            let previewUrl = "";
            if (matches && matches.length) {
              previewUrl = matches[0];
              console.log('Preview url found:', previewUrl);
            }
            console.log("No preview url found.");
            core.setOutput('vercel_preview_url', previewUrl);

      - name: Checkout
        if: ${{ steps.get_preview_url.outputs.vercel_preview_url != '' }}
        uses: actions/checkout@v3

      - name: Setup Node.JS
        if: ${{ steps.get_preview_url.outputs.vercel_preview_url != '' }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install deps
        if: ${{ steps.get_preview_url.outputs.vercel_preview_url != '' }}
        run: yarn install --frozen-lockfile

      - name: Run static test
        if: ${{ steps.get_preview_url.outputs.vercel_preview_url != '' }}
        run: yarn lint

      - name: Run test suite
        if: ${{ steps.get_preview_url.outputs.vercel_preview_url != '' }}
        run: yarn test:ci

      - name: Startup app as localhost
        if: ${{ steps.get_preview_url.outputs.vercel_preview_url != '' }}
        run: yarn dev

      - name: Replace URL domain of a11y config
        uses: actions/github-script@5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const json = require('../../.pa11yci-base.json');

            const vercel_url = ${{ steps.get_preview_url.outputs.vercel_preview_url }};

            json.urls = json.urls.map((url) => vercel_url + url);

            fs.appendFileSync('../../.pa11yci', JSON.stringify(json));

      - name: Run a11y test
        if: ${{ steps.get_preview_url.outputs.vercel_preview_url != '' }}
        run: yarn test:a11y
